apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  wp-env: {{ .Values.app.environment | quote }}
  wp-home: "https://{{ .Values.ingress.host }}"
  wp-siteurl: "https://{{ .Values.ingress.host }}/wp"
  apache-vhost-dir: "/var/www/html/public"
  redis-host: "{{ .Release.Name }}-redis-master"
  
